### ISSUE TITLE
loftsman.log files as far as the eye can see

### ISSUE THREAD

**Issue by nerscchris** [Cray-HPE/loftsman#12]
Hi there,

I've noticed that whenever loftsman is (say to validate a manifest) it leaves a `loftsman.log` file behind in the current working directory, and I cannot see a way to disable that.  I've added them to my `.gitignore` to stop them getting committed but it would be nice if it was possible to override this behaviour in some way, perhaps by being able to specify the `--json-log-path` value via an environment variable please?

All the best,
Chris

**Comment by rockholla** [comment]
Hi Chris, I think it would be reasonable to add a `--disable-local-log-file` or some kind of approach like that.

A little background/context here, some of the initial built-in logging choices were at least somewhat based on internal Cray/HPE needs, and I figured we'd revisit slightly at some point, though I'm not sure I predicted any major frustration in the current implementation, so apologies if that's the case.

Another point of context here: The loftsman cli is first and foremost designed to be a tool to be used in pipelines and other automated processes, so the idea of maintaining logs and other artifacts for persisting in these use-cases hopefully provides some clarity around the current design and implementation.

I'm marking this one for work nonetheless, as I do believe some further options around logging generally would be a good idea. Thanks!
