### ISSUE TITLE
Provide some example manifests/schema documentation

### ISSUE THREAD

**Issue by rvesse** [Cray-HPE/loftsman#14]
For those encountering Loftsman for the first time and who were not already exposed to it internally at Cray/HPE this repository does not really provide any easy to find examples of manifests.  (I know there are some buried in the tests but those aren't obvious).

It would be nice if the `README.md` provided a minimalist example of a manifest, and if there was a more in-depth doc on the schema and how to construct a manifest (and or a folder of example manifests).  Again I am aware that `loftsman manifest create` sub-command exists but it literally just leaves all the fields users actually want to fill out blank without leaving any placeholders for users to follow.

**Comment by rockholla** [comment]
Hi Rob, thanks for putting this in, and agreed. I've been trying to figure out some final details with what we do for the OSS docs here as we move into this stage. Examples of manifests and working with manifests are at the top of the list for that, so marking as such here. I'm still hard at work on continuing to make next moves for Loftsman v1, so I'll include this.

**Comment by rockholla** [comment]
We have some [initial docs in place now](https://github.com/Cray-HPE/loftsman/tree/main/docs) and [a place with some manifest examples per schema version](https://github.com/Cray-HPE/loftsman/tree/main/schemas/manifests/v1beta1/examples). Just let me know if you have any other requests on this front, Rob.

**Comment by rvesse** [comment]
LGTM, thanks 👍
