### ISSUE TITLE
Request for documentation on how end users should use loftsman

### ISSUE THREAD

**Issue by nerscchris** [Cray-HPE/loftsman#6]
Hi there all,

As us folks at NERSC have a Shasta system that we're working on configuring it would be very useful to have some documentation on how to write a manifest or chart for loftsman in order to be able to deploy our own services with it.

For instance I started looking at the helm docs to create a chart for our own Slurm deployment but that starts off with the guidance to run `helm create [chart-name]` but if I run `loftsman helm create nersc-slurm` as an unprivileged user to create that structure in my checked out git repo for our configs it just errors out with:
```
Error: Cannot run ad hoc calls, as the last know shaper status is 'The connection to the server localhost:8080 was refused - did you specify the right host or port?', shaper status 'Succeeded' is required before running ad hoc calls.
```
I presume it is trying to talk to kubernetes there, which I wouldn't have thought would be necessary (or desired) for what I'm trying to achieve.

All the best!
Chris

**Comment by rockholla** [comment]
Hi Chris,

So, this open source repo will be dedicated to Loftsman v1 and forward only. The docs/help requested here are for the v0.x. I'd suggest that you reach out to us directly for support on this issue as we'll not really be using anything here for support of Loftsman in its previous versions. I'm happy to help directly in that way, look forward to hearing from you!

Patrick

**Comment by nerscchris** [comment]
Hi Patrick,

Understood, and thanks so much for the chat elsewhere! 

We will need v1 docs at some point too, but you are quite right, at the moment I was asking about v0.

All the best & hope you're keeping well,
Chris
